# Generated by Django 2.1.7 on 2019-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceIP', models.CharField(max_length=32)),
                ('distIP', models.CharField(max_length=32)),
                ('communicationCunt', models.IntegerField()),
            ],
        ),
    ]
