# Generated by Django 2.2 on 2019-04-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_binarystore'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('eth_src', models.BinaryField(max_length=6)),
                ('eth_dst', models.BinaryField(max_length=6)),
                ('eth_type', models.IntegerField()),
                ('ip_src', models.BinaryField(max_length=16)),
                ('ip_dst', models.BinaryField(max_length=16)),
                ('ip_proto', models.IntegerField()),
                ('trans_sport', models.IntegerField()),
                ('trans_dport', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='binarystore',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
