# Generated by Django 2.2 on 2019-04-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('eth_src', models.CharField(max_length=32)),
                ('eth_dst', models.CharField(max_length=32)),
                ('eth_type', models.IntegerField()),
                ('ip_src', models.CharField(max_length=64)),
                ('ip_dst', models.CharField(max_length=64)),
                ('ip_proto', models.IntegerField()),
                ('trans_sport', models.IntegerField()),
                ('trans_dport', models.IntegerField()),
                ('comm_way', models.CharField(default='Unknown', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IpHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('host', models.CharField(max_length=64)),
            ],
        ),
    ]
