# Generated by Django 2.2 on 2019-04-23 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldsInfo',
        ),
    ]
