# Generated by Django 2.2 on 2019-04-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0002_delete_fieldsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('eth_src', models.CharField(max_length=32)),
                ('eth_dst', models.CharField(max_length=32)),
                ('eth_type', models.CharField(max_length=32)),
                ('ip_src', models.CharField(max_length=64)),
                ('ip_dst', models.CharField(max_length=64)),
                ('ip_proto', models.CharField(max_length=32)),
                ('trans_sport', models.IntegerField()),
                ('trans_dport', models.IntegerField()),
                ('comm_way', models.CharField(default='Unknown', max_length=32, null=True)),
            ],
        ),
    ]
