# Generated by Django 2.2 on 2019-07-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0003_fieldsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RgBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('eth_src', models.CharField(max_length=32)),
                ('eth_dst', models.CharField(max_length=32)),
                ('eth_type', models.CharField(max_length=32)),
                ('ip_src', models.CharField(max_length=64)),
                ('ip_dst', models.CharField(max_length=64)),
                ('ip_proto', models.CharField(max_length=32)),
                ('trans_sport', models.IntegerField()),
                ('trans_dport', models.IntegerField()),
                ('comm_way', models.CharField(default='Unknown', max_length=32, null=True)),
                ('host_src', models.CharField(max_length=64)),
                ('host_dst', models.CharField(max_length=64)),
            ],
        ),
    ]
