# Generated by Django 2.2 on 2019-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rg', '0004_rgbaseinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rgbaseinfo',
            name='host_dst',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='rgbaseinfo',
            name='host_src',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
